# --------------------------------------------------------------------
# Tailscale 专属网络路由规则 (TAILSCALE 策略)
# 用于将 Tailscale 的虚拟局域网 IP 段及内网域名分流至对应接口
# --------------------------------------------------------------------

DOMAIN-WILDCARD,tail*.ts.net,TAILSCALE
DOMAIN-SUFFIX,ts.net,TAILSCALE
IP-CIDR,100.64.0.0/10,TAILSCALE
